---
title: "IIA Supply Chain Optimization Brief"
output:
  pdf_document: default
  header-includes:
  - \usepackage{color}
---



\section{Problem}

\subsection{ROI}

In 2016, e-commerce sales totaled an estimated $394.9 billion, accounting for 8.1 percent of total annual sales. This total was a 15 percent increase from 2015. Advances in technology and adoption of the internet has forced the retail industry to make dramatic shifts toward e-commerce. While this presents a tremendous opportunity for business growth, the cost associated with inefficiencies in supply chains makes optimally allocating inventory to fulfillment centers integral to retailers' success. Customer retention and loyalty requires the business to deliver products quickly and efficiently, so inventory allocation to fulfillment centers must account for two primary factors:

+ item cost of delivering units from fulfillment centers to delivery addresses
+ length of time required to fulfill orders to delivery addresses from fulfillment centers

While the first of these costs can be associated with a particular dollar value, the cost related to the second consideration is driven by customer disatisfaction with delayed product arrivals and is more difficult to quantify. Additionally, there are a host of other factors to be considered when optimizing inventory allocation. These include the cost of transferring units between fulfillment centers to respond to shifts in demand, as well as decisions about whether to fulfill online orders from stores instead of dedicated fulfillment centers. In the following sections, we propose a method to determine the proper allocation of inventory to fulfillment centers. Our method assumes that no transfers are
made between fulfillment centers and that e-commerce orders are fulfilled only from dedicated fulfillment centers and no orders will be fulfilled by stores, however, potential future work could be explored by relaxing these assumptions.

\subsection{Technical Complexity}

\subsubsection{ [Typical Solution] How they work:}

There are several products on the market for supply chain optimization. Many of those products are outfitted with the functionality for determining efficient allocation of inventory to distribution centers. The common approach to optimizing inventory allocation decomposes into two primary tasks: predicting future inventory demand and then given this forecast, develop a plan to purchase and distribute products so as to meet the demands at each fulfillment center in the most cost efficient way possible.

Demand predictions are made by fitting statistical models using past demand as well as predicted future events to forecast future demand. Often, these forecasts are done using data that has been aggregated to a fairly high level, such as by week, subpopulation of customers, category of merchandise, etc, though new technical ability to store and access large amounts of data quickly allows demand forecasting to be done at a far more granular level, such as at the daily level, per item per customer. Safety stock is the extra stock kept on hand to mitigate rish of inventory depletion due to unpredictability in demand. 

The \textit{service level} refers to the probability of the period-specific demand quantity exceeding the inventory quantity on hand:

$\alpha = Prob\left(\mbox{period demand} \le \mbox{available inventory stock}\right)$.

A distributor sets safety stock levels at any given fulfillment center so that the center's service level low with the intent to minimize the loss in sales due to the inability to fulfill orders, increasing customer retention. However, too much safety stock leads to unnecessary costs, which makes finding the appropriate balance between too much and too little essential for efficient distribution. 

Once an adequate demand prediction is and the uncertainty with this forecast is quantified, retailers determine the product buy - the amount of product to purchase for order fulfillment, and which e-commerce fulfillment center fulfills each online order using a set of rules which specify the logic necessary for minimizing the cost of shipping orders from fulfillment centers to delivery locations and the amount of time required for products to be delivered to the customer. 

\subsubsection{Typical Solutions: Why they suck} 

Despite the numerous existing applications offering solutions to the allocation problem, distribution inefficiencies are still quite prevelant. The underperformance of many tools can be attributed to one of more key shortcomings, the first of which is that they rely on rigid assumptions about the distribution of future product demand for a given fulfillment center. For example, many universally accepted methods assume that safety stock is proportional to the standard deviation of the demand, which is assumed to follow a Normal distribution. 

{\color{red} HERE IS WHERE WE WILL PUT A PRETTY EXAMPLE PICTURE OF WHY ASSUMING NORMALITY IS BAD. HERE IS WHERE I NEED JOSH'S HELP EXPLAINING WHY THIS ASSUMPTION IS BAD -- MAKE SOME SORT OF REFERENCE TO A HIGHLY RIGHT-SKEWED DISTRIBUTION}

It is also common in the existing market for software solutions to assume that the demand at a given fulfillment center is independent from week to week, i.e. that the demand in the current week contains useful information for predicting demand for the week to follow. In most practical situations, this assumption is invalid due to the innate dependency between time and demand. The classic example is the trendsetter: she purchases an item and after wearing it, the crowd follows suit and demand for a given product increases until it reaches a certain point at which the market is saturated.

{\color{red} OR MAYBE WE PUT THE GRAPHIC HERE. I DON'T KNOW - I REVERT TO THE STORY WIZARDS.}

Whenever these assumptions about the variability in demand are invalid, the calculations that many existing products use to determine the buy quantity for a given service level will be incorrect. This leads to loss due to either

\begin{itemize}
\item access inventory after overbuying, which will either be wasted or discounted
\item sales loss as a result of not being able to meet consumer demand.
\end{itemize}

Some packages offer more sophisticated methods of forecasting demand than others, and in some cases, much more sophisticated.  Once a retailer obtains an adequate forecast for the demand, it is a straightforward task to determine the \textit{optimal initial allocation}, or the amount of inventory each fulfillment center should receive, based on their geographic locations and the demand predicted for the region that is serviced by a particular center. However, despite the quality of a predictive model, there is error associated with any prediction. Most existing inventory allocation tools determine the best initial allocation of inventory to fulfillment centers by assuming that this prediction error doesn't exist, but the uncertainty in demand prediction is inherited in the allocation that is best for a given demand prediction. Failure to account for the uncertainty in this allocation will lead to suboptimal allocation of inventory, leading to loss incurred due to fulfillment centers with overstock or inability to fulfill customer orders where the demanded exceed projections.

{\color{red} PICTURE HERE TO EXPLAIN WHY THIS IS BAD AND HOW DISASTER COULD BE MITIGATED BY AVERAGING OVER THE SET OF ALL POSSIBLE ALLOCATIONS.}

We propose an approach for determining inventory allocation by accounting for the uncertainty in the optimal distribution of inventory. Using a Bayesian approach allows us to consider the what-ifs  


\section{Solution}



When forecasting on-line sales, we start with a set of households, denoted $\mathcal{H}$.  Although it is possible to forecast purchases at the household level, forecasting models are usually build at an aggregate level.  For example, we might create forecasts within political boundaries (\emph{e.g.,} county or state) or within designated marketing areas.  Define a partition $\mathcal{P}$ of $\mathcal{H}$, so $\mathcal{P} = \{P_1, P_2, ..., P_K \}$, where $P_k \cap P_{k'} = \emptyset$ for all $k$ and $k'$ and $\bigcup_k P_k = \mathcal{H}$.  The elements of this partition constitute the set of regions for which forecasts are created.

For simplicity of modeling, we assume that forecasting for the SKU of interest has been performed taking a Bayesian approach, so the retailer has posterior distributions for each of the parameters in the forecasting model.  Denote the historical demand data from which the forecasting model was constructed $\mathbf{Y}$ and the historical independent variables used to predict demand $\mathbf{X}$.  Denote the set of parameters in the model $\boldsymbol{\theta}$.  Using a Bayesian approach, the forecasting model has a posterior distribution for $\boldsymbol{\theta}$,

$$\pi (\boldsymbol{\theta} \mid \mathbf{Y}, \mathbf{X}) \propto \pi (\mathbf{Y} \mid \boldsymbol{\theta}, \mathbf{X}) \pi (\boldsymbol{\theta}).$$

\noindent For the purpose of forecasting future sales, we assume that future values of the independent variables are known.  We denote those future values $\mathbf{X}^*$.  Similarly, we denote future values of demand $\mathbf{Y}^*$.  The predictive distribution of $\mathbf{Y}^*$ is

$$\pi (\mathbf{Y}^* \mid \mathbf{X}^*, \mathbf{Y}, \mathbf{X}) = \int_{\boldsymbol{\Theta}} \pi (\mathbf{Y}^* \mid \boldsymbol{\theta}, \mathbf{X}^*) \pi (\boldsymbol{\theta} \mid \mathbf{Y}, \mathbf{X}) d \boldsymbol{\theta}$$.

\noindent We assume that forecasting is performed over a finite set of time points, $1, \ldots, T$ within each region.  The forecast in region $k$ at time $t$ is denoted $Y_{kt}^*$.  The total demand across all time points and regions is denoted $D^*$, and

$$D^* = \sum_{t = 1}^T \sum_{k = 1}^K Y_{kt}^*.$$



\subsection{Optimize over everything to account for uncertainty in demand predictions}
  
\subsection{But how? Math!}
  
\section{After}

* Output -> Outcome -> minimize loss -> increase ROI 